### ISSUE TITLE
createAlias is not working with plastic-criteria plugin

### ISSUE THREAD

**Issue by shivoodles** [fabiooshiro/plastic-criteria#12]
I am using criteria in test case like 
def userCompanyRoleMapping = UserCompanyRoleMapping.withCriteria {
			createAlias('company', 'c')
			eq('user', user)
}

it gives error
groovy.lang.MissingMethodException: No signature of method: plastic.criteria.PlasticCriteria.createAlias() is applicable for argument types: (java.lang.String, java.lang.String) values: [company, c]
	at plastic.criteria.PlasticCriteria.methodMissing(PlasticCriteria.groovy:132)
	at com.threebaysover.UserServiceSpec.setup_closure4(UserServiceSpec.groovy:100)
	at plastic.criteria.PlasticCriteria.list(PlasticCriteria.groovy:181)
	at plastic.criteria.PlasticCriteria.mockCriteria_closure20(PlasticCriteria.groovy:61)
	at com.threebaysover.UserServiceSpec.setup(UserServiceSpec.groovy:99)

**Comment by shivoodles** [comment]
It is resolved in version 1.5.1
