### ISSUE TITLE
"countDistinct" in criteria projection won't work

### ISSUE THREAD

**Issue by dtamm** [fabiooshiro/plastic-criteria#17]
Using "countDistinct" in a criteria projection won't work. it will lead to the following exception:

```
groovy.lang.MissingMethodException: No signature of method: plastic.criteria.PlasticCriteria.countDistinct() is applicable for argument types: (java.lang.String) values: [id]
Possible solutions: listDistinct(java.lang.Object)
	at plastic.criteria.PlasticCriteria.methodMissing(PlasticCriteria.groovy:145)
	at package.TestService$_closure5.closure37$_closure39(TestService.groovy:458)
	at plastic.criteria.PlasticCriteria.projections(PlasticCriteria.groovy:134)
	at package.TestService.closure5$_closure37(TestService.groovy:457)
	at plastic.criteria.PlasticCriteria.list(PlasticCriteria.groovy:194)
	at package.TestService$_closure5.doCall(TestService.groovy:456)
	at package.TestController$_closure12.doCall(TestController.groovy:409)
	at filter.TestSpec.Check, if specific rights are given_closure8(TestSpec.groovy:185)
	at grails.test.mixin.web.FiltersUnitTestMixin.withFilters(FiltersUnitTestMixin.groovy:112)
	at filter.KundeBerechtigungSpec.Check, if specific rights are given(TestSpec.groovy:184)
```

Using "count" instead of "countDistinct" will not recieve the same result.

**Comment by fabiooshiro** [comment]
please upgrade to the new version 1.6
